{% set name = "spec2nexus" %}
{% set version = "2021.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba4d18ea37795fb2385fab8e2ee408b7f4756ee747aa80b06da0d3b0db5ff325

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - extractSpecScan = spec2nexus.extractSpecScan:main
    - spec2nexus = spec2nexus.nexus:main
    - specplot = spec2nexus.specplot:main
    - specplot_gallery = spec2nexus.specplot_gallery:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - h5py
    - lxml
    - matplotlib-base
    - numpy

test:
  requires:
    - pip
    - setuptools-scm
  imports:
    - spec2nexus
    - spec2nexus.spec
  commands:
    - pip check
    - extractSpecScan -h
    - spec2nexus --version
    - spec2nexus -h
    - specplot -h
    - specplot_gallery -h

about:
  home: https://github.com/prjemian/spec2nexus
  license: CC-BY-4.0
  license_family: CC
  license_file: {{ name }}/LICENSE.txt
  summary: command-line tool to convert SPEC data files to NeXus HDF5
  description: |
    spec2nexus converts SPEC data files and scans into NeXus HDF5 files.
    It is pure Python code with few dependencies.
  doc_url: https://prjemian.github.io/spec2nexus
  dev_url: https://github.com/prjemian/spec2nexus

extra:
  recipe-maintainers:
    - prjemian
