{% set name = "spec2nexus" %}
{% set version = "2021.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a72bc84a41fcca01a1f9b76ede6a9a46852d574cd2c864e6db8cc45c10243633

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - extractSpecScan = spec2nexus.extractSpecScan:main
    - spec2nexus = spec2nexus.nexus:main
    - specplot = spec2nexus.specplot:main
    - specplot_gallery = spec2nexus.specplot_gallery:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - h5py
    - lxml
    - matplotlib-base
    - numpy

test:
  requires:
    - pip
  imports:
    - spec2nexus
  commands:
    - pip check
    - extractSpecScan -h
    - spec2nexus --version
    - spec2nexus -h
    - specplot -h
    - specplot_gallery -h

about:
  home: https://github.com/prjemian/spec2nexus
  license: CC-BY-4.0
  license_family: CC
  license_file: src/{{ name }}/LICENSE.txt
  summary: 'command-line tool to convert SPEC data files to NeXus HDF5'
  description: |
    spec2nexus converts SPEC data files and scans into NeXus HDF5 files.
    It is pure Python code with few dependencies.
  doc_url: https://prjemian.github.io/spec2nexus
  dev_url: https://github.com/prjemian/spec2nexus

extra:
  recipe-maintainers:
    - prjemian
