{% set name = "spec2nexus" %}
{% set version = "2021.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28a591a830fc0283c2f889c9a4b30c261846c996501be63b8d6bd1d46c005677

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - extractSpecScan = spec2nexus.extractSpecScan:main
    - spec2nexus = spec2nexus.nexus:main
    - specplot = spec2nexus.specplot:main
    - specplot_gallery = spec2nexus.specplot_gallery:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - h5py
    - lxml
    - matplotlib-base
    - numpy

test:
  requires:
    - pip
    - setuptools-scm
    - python {{ python_min }}
  imports:
    - spec2nexus
    - spec2nexus.spec
  commands:
    - pip check
    - extractSpecScan -h
    - spec2nexus --version
    - spec2nexus -h
    - specplot -h
    - specplot_gallery -h

about:
  home: https://github.com/prjemian/spec2nexus
  license: CC-BY-4.0
  license_family: CC
  license_file: {{ name }}/LICENSE.txt
  summary: command-line tool to convert SPEC data files to NeXus HDF5
  description: |
    spec2nexus converts SPEC data files and scans into NeXus HDF5 files.
    It is pure Python code with few dependencies.
  doc_url: https://prjemian.github.io/spec2nexus
  dev_url: https://github.com/prjemian/spec2nexus

extra:
  recipe-maintainers:
    - prjemian
